CREATE TABLE IF NOT EXISTS "stride-studio_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stride-studio_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"athlete_id" integer NOT NULL,
	"strava_activity_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "stride-studio_activity_strava_activity_id_unique" UNIQUE("strava_activity_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stride-studio_athlete" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stride-studio_athlete_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"strava_athlete_id" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "stride-studio_athlete_strava_athlete_id_unique" UNIQUE("strava_athlete_id")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stride-studio_activity" ADD CONSTRAINT "stride-studio_activity_athlete_id_stride-studio_athlete_id_fk" FOREIGN KEY ("athlete_id") REFERENCES "public"."stride-studio_athlete"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_athlete_id_idx" ON "stride-studio_activity" USING btree ("athlete_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_strava_activity_id_idx" ON "stride-studio_activity" USING btree ("strava_activity_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "athlete_strava_athlete_id_idx" ON "stride-studio_athlete" USING btree ("strava_athlete_id");